"""Seed database of known AI organizations for deterministic entity resolution.
Canonical name -> known aliases/variants seen in the wild. Extend as needed.
This is a static, hand-curated reference list — not scraped — used purely as a
lookup table, so there is no provenance/hallucination concern for its contents.
"""

SEED_ENTITIES: dict[str, list[str]] = {
    "OpenAI": ["OpenAI", "Open AI", "OpenAI, Inc.", "OpenAI Inc", "OpenAI Incorporated"],
    "Anthropic": ["Anthropic", "Anthropic PBC", "Anthropic, PBC"],
    "Google DeepMind": ["DeepMind", "Google DeepMind", "Deep Mind"],
    "Meta AI": ["Meta AI", "Meta Platforms AI", "FAIR", "Facebook AI Research"],
    "Microsoft AI": ["Microsoft AI", "Microsoft Research AI"],
    "Mistral AI": ["Mistral", "Mistral AI", "Mistral AI SAS"],
    "Cohere": ["Cohere", "Cohere Inc", "Cohere AI"],
    "xAI": ["xAI", "X.AI", "x.ai Corp"],
    "Stability AI": ["Stability AI", "Stability.ai", "Stability AI Ltd"],
    "Hugging Face": ["Hugging Face", "HuggingFace", "Hugging Face Inc"],
    "Perplexity AI": ["Perplexity", "Perplexity AI", "Perplexity AI Inc"],
    "Scale AI": ["Scale AI", "Scale.ai", "Scale AI Inc"],
    "Databricks": ["Databricks", "Databricks Inc"],
    "Together AI": ["Together AI", "Together.ai", "Together Computer"],
    "Adept AI": ["Adept", "Adept AI", "Adept AI Labs"],
    "Inflection AI": ["Inflection", "Inflection AI"],
    "Character.AI": ["Character.AI", "Character AI", "CharacterAI"],
    "Runway": ["Runway", "Runway ML", "RunwayML"],
    "Midjourney": ["Midjourney", "Midjourney Inc"],
    "ElevenLabs": ["ElevenLabs", "Eleven Labs"],
    "Cerebras Systems": ["Cerebras", "Cerebras Systems"],
    "Groq": ["Groq", "Groq Inc"],
    "SambaNova Systems": ["SambaNova", "SambaNova Systems"],
    "AI21 Labs": ["AI21", "AI21 Labs"],
    "Aleph Alpha": ["Aleph Alpha", "Aleph Alpha GmbH"],
    "DeepSeek": ["DeepSeek", "DeepSeek AI", "Deepseek"],
    "Moonshot AI": ["Moonshot AI", "Moonshot"],
    "01.AI": ["01.AI", "01 AI", "Zero One AI"],
    "Baichuan AI": ["Baichuan", "Baichuan AI"],
    "Zhipu AI": ["Zhipu", "Zhipu AI", "ChatGLM"],
    "Nvidia": ["Nvidia", "NVIDIA Corporation", "NVIDIA Corp"],
    "IBM Watson": ["IBM Watson", "Watson"],
    "Salesforce AI": ["Salesforce AI", "Salesforce Einstein", "Einstein AI"],
    "Snowflake": ["Snowflake", "Snowflake Inc", "Snowflake Computing"],
    "Palantir": ["Palantir", "Palantir Technologies"],
    "C3 AI": ["C3.ai", "C3 AI", "C3.ai Inc"],
    "UiPath": ["UiPath", "UiPath Inc"],
    "Glean": ["Glean", "Glean Technologies"],
    "Harvey AI": ["Harvey", "Harvey AI"],
    "Sierra": ["Sierra", "Sierra AI"],
    "Cursor (Anysphere)": ["Cursor", "Anysphere", "Anysphere Inc"],
    "Replit": ["Replit", "Replit Inc"],
    "GitHub Copilot (Microsoft)": ["GitHub Copilot", "Copilot"],
    "Synthesia": ["Synthesia", "Synthesia Ltd"],
    "Jasper AI": ["Jasper", "Jasper AI", "Jasper.ai"],
    "Writer": ["Writer", "Writer Inc", "Writer.com"],
    "Weights & Biases": ["Weights & Biases", "Weights and Biases", "W&B", "WandB"],
    "LangChain": ["LangChain", "Langchain Inc", "LangChain AI"],
    "Pinecone": ["Pinecone", "Pinecone Systems"],
    "Weaviate": ["Weaviate", "Weaviate B.V."],
    "Chroma": ["Chroma", "ChromaDB", "Chroma Inc"],
}
